/* eslint-disable camelcase */
import type { Metadata } from 'next'
import { Nova_Round } from 'next/font/google'
import '../assets/styles/globals.css'

const inter = Nova_Round({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  )
}
