import type { Metadata } from 'next'
import { Nova_Round } from 'next/font/google'
import '../assets/styles/globals.css'
import '../assets/styles/section-gallery.css'

const NR = Nova_Round({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-NR',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${NR.variable}`}>{children}</body>
    </html>
  )
}
